### ISSUE TITLE
Insert image button seems to disappear with fastwiki enabled

### ISSUE THREAD

**Issue by GJRobert** [zioth/dokuwiki_fastwiki#27]
I found that when I enable fastwiki (using bootstrap3 template too), the button in edit mode to insert images or media is disappearing.
![2017-01-25_23-27-34](https://cloud.githubusercontent.com/assets/655584/22296713/0f68b060-e356-11e6-93d8-fba64823472b.png)
(Sorry if this is a duplicate)

**Comment by GJRobert** [comment]
Some other buttons like the Insert Wikilink button, Bootstrap Wrapper button, are missing too. (Just found today)

**Comment by zioth** [comment]
Sorry I haven't had a chance to look at this yet. I haven't forgotten; I'm just really busy right now.

**Comment by GJRobert** [comment]
I found today that the editor used by [plugin:discussion](http://www.dokuwiki.org/plugin:discussion) also has this problem. So maybe it's a good start to look for the common inclusion used by fastwiki and discussion, to troubleshoot why certain buttons are missing in the inline editors.

**Comment by GJRobert** [comment]
It seems that the toolbars used by plugin:fastwiki and plugin:discussion are the same, and both of them have taken buttons opening new windows or overlays (usually with a little black triangle on the top-right corner) out. Perhaps this is designed in the core of DokuWiki on purpose. But I still hope that the toolbar of fastwiki can be full functional.

**Comment by zioth** [comment]
@GJRobert What template are you using? The wikilink and media buttons work fine for me. Maybe fastwiki is triggering a bug in your template.

fastwiki doesn't have its own special toolbar. It just calls the built-in initToolbar() function. If there are special features of templates and plugins which override that functionality (adding a button on page load instead of hooking into the normal mechanism), then that will break. Otherwise, all buttons should work.

**Comment by GJRobert** [comment]
Hi @zioth you are really right. I have installed a new DW instance with only fastwiki enabled: buttons appearing normally.

But if plugin:discussion is also installed and enabled, then in both toolbars on fastwiki inline editing and discussion textarea, wikilink and media buttons will not display. I found that this is [a design of discussion plugin](https://github.com/dokufreaks/plugin-discussion/issues/168 "no button for the media manager · Issue #168 · dokufreaks/plugin-discussion").

I will report to plugin:discussion and try to find out why it modify its toolbar but also affects fastwiki toolbar.

Thanks for your information!

**Comment by Klap-in** [comment]
For the discussion plugin some trics are used to add a toolbar to the comment field. This toolbar is simplified as well. I guess this simplification hits also toolbars that are added in other situations.

Maybe it requires a redesign of the toolbar code, so that it is easier to add a (customized) toolbar.

**Comment by zioth** [comment]
@Klap-in @GJRobert 

In discussion/script.js, I see this line:
initToolbar("discussion__comment_toolbar", "discussion__comment_text", toolbar);

I believe this is what's overriding the default toolbar. There's nothing I can do in fastwiki to fix it, without breaking either the discussion plugin, or plugins which deliberately change the toolbar. The bug could be fixed in dokuwiki by allowing multiple toolbars (unlikely that change will be made or accepted), or in discussion. The easiest way to fix it in discussion would be with a new config option which prevents initToolbar from being called in that way.

Since there's nothing I can do about it, I'm going to close this ticket. Sorry. :(
